services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.12-ubi9
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
