services:
  sf-api_serve:
    image: local/sf-api:serve
    ports:
      - "80:8080"
    build:
      context: ..
      target: serve
    env_file: docker.env
    depends_on:
      - mongodb
  sf-api_cron:
    image: local/sf-api:cron
    build:
      context: ..
      target: cron
    env_file: docker.env
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:7.0.12-ubi9
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
