services:
  sf-api_serve:
    image: local/sf-api:serve
    ports:
      - "80:8080"
    build:
      context: ..
      target: serve
    env_file: docker.env
    environment:
      - WB_TESTING_KEY=${WB_TESTING_KEY}
      - MONGO_CONNECTION_URL=${MONGO_CONNECTION_URL}

  sf-api_cron:
    image: local/sf-api:cron
    build:
      context: ..
      target: cron
    env_file: docker.env
    environment:
      - WB_TESTING_KEY=${WB_TESTING_KEY}
      - MONGO_CONNECTION_URL=${MONGO_CONNECTION_URL}
