services:
  sf-api_serve:
    image: local/sf-api:serve
    build:
      context: ..
      target: serve
    env_file: docker.env
    depends_on:
      - mongodb
  sf-api_cron:
    image: local/sf-api:cron
    build:
      context: ..
      target: cron
    env_file: docker.env
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:7.0.12-ubi9
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./mongo_data
        target: /data/db
